# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  schedule:
    - cron: '0 0 * * *'
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  bumpVersion:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' && contains(github.event.head_commit.message, '[bot]') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Init git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Bump Package Version
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            pnpm version prepatch -m "ðŸš€ Bump version to %s"
          elif [[ ${{ github.event_name }} == 'schedule' ]]; then
            pnpm version prerelease -m "ðŸš€ Bump version to %s"
          fi

      - name: Push changes
        run: |
          git push origin main
  build:
    runs-on: ubuntu-latest
    needs: bumpVersion
    if: ${{ always() }} && contains(github.event.head_commit.message, '[bot]') == false
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - id: commit
        name: Get commit Hash
        uses: pr-mpt/actions-commit-hash@v2

      - name: Init git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache/restore@v3
        id: cache-restore
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            /home/runner/.cache/puppeteer
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}

      - name: Install dependencies
        run: pnpm install

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Save env as .env.local
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_GIT_HASH=${{ steps.commit.outputs.hash }}" >> .env.local
          echo "NEXT_PUBLIC_GIT_HASH_SHORT=${{ steps.commit.outputs.short }}" >> .env.local
          echo "NEXT_PUBLIC_RUN_ID=${{ github.run_id }}" >> .env.local

      - name: Prepare build
        run: pnpm preBuild

      - name: Build with Next.js
        id: buildNextJS
        run: pnpm next build
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_GIT_HASH: ${{ steps.commit.outputs.hash }}
          NEXT_PUBLIC_GIT_HASH_SHORT: ${{ steps.commit.outputs.short }}
          NEXT_PUBLIC_RUN_ID: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OUTPUT: ${{ env.GITHUB_OUTPUT }}

      - name: Static HTML export with Next.js
        run: pnpm next export
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_GIT_HASH: ${{ steps.commit.outputs.hash }}
          NEXT_PUBLIC_GIT_HASH_SHORT: ${{ steps.commit.outputs.short }}
          NEXT_PUBLIC_RUN_ID: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save cache
        uses: actions/cache/save@v3
        id: cache-save
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            /home/runner/.cache/puppeteer
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

      - name: Create tar.gz
        run: tar -czvf out.tar.gz out

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.package-version.outputs.current-version }}
          prerelease: false
          title: ${{ steps.package-version.outputs.current-version }}
          files: |
            out.tar.gz

      - name: Generate Summary
        run: |
          echo "## Job Summary (${{ steps.date.outputs.date }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Key | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| -- | -- |" >> $GITHUB_STEP_SUMMARY
          echo "| Version | ${{ steps.package-version.outputs.current-version}} |" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | [${{ steps.commit.outputs.short }}](https://github.com/DerTyp7214/Portfoio/commit/${{ steps.commit.outputs.hash }}) |" >> $GITHUB_STEP_SUMMARY
          echo "| Job | [${{ github.run_id }}](https://github.com/DerTyp7214/Portfoio/actions/runs/${{ github.run_id }}) |" >> $GITHUB_STEP_SUMMARY
          echo "| Cached Image Count | ${{ steps.buildNextJS.outputs.count }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Cached Image Size | ${{ steps.buildNextJS.outputs.size }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Cache Duration | ${{ steps.buildNextJS.outputs.duration }} |" >> $GITHUB_STEP_SUMMARY

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
